# Generated by Django 2.1.1 on 2018-10-03 13:00

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180905_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='namespace',
            field=models.ForeignKey(default='it.polimi', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='namespace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='institution',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'namespace')},
        ),
    ]
